# Generated by Django 4.1.3 on 2023-01-25 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Visibility', models.CharField(choices=[('Отображать', 'Отображать'), ('Не отображать', 'Не отображать')], default='Отображать', max_length=50, verbose_name='Отображение')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='certificate/image/', verbose_name='Изображение')),
                ('File', models.FileField(null=True, upload_to='certificate/file/', verbose_name='Фаил')),
            ],
            options={
                'verbose_name': 'Сертификаты',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to='product/images/')),
            ],
            options={
                'verbose_name': 'Изображения товаров',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='product/', verbose_name='Изображение')),
                ('Description', models.TextField(blank=True, verbose_name='Описание')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('Visibility', models.CharField(choices=[('Отображать', 'Отображать'), ('Не отображать', 'Не отображать')], default='Отображать', max_length=50, verbose_name='Отображение')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
                ('Images', models.ManyToManyField(blank=True, to='web.productimage', verbose_name='Изображения товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
    ]
