# Generated by Django 4.1.3 on 2023-01-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='service/', verbose_name='Изображение')),
                ('Description', models.TextField(blank=True, verbose_name='Описание')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('Visibility', models.CharField(choices=[('Отображать', 'Отображать'), ('Не отображать', 'Не отображать')], default='Отображать', max_length=50, verbose_name='Отображение')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to='service/images/')),
            ],
            options={
                'verbose_name': 'Изображения услуги',
                'verbose_name_plural': 'Изображения услуги',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='service',
            name='Images',
            field=models.ManyToManyField(blank=True, to='web.serviceimage', verbose_name='Изображения услуги'),
        ),
    ]
