# Generated by Django 4.1.3 on 2023-01-26 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_service_serviceimage_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to='portfolio/images/')),
            ],
            options={
                'verbose_name': 'Изображения портфолио',
                'verbose_name_plural': 'Изображения портфолио',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуга'},
        ),
        migrations.AlterField(
            model_name='service',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_service', to='web.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='portfolio/', verbose_name='Изображение')),
                ('Description', models.TextField(blank=True, verbose_name='Описание')),
                ('Wasted_time', models.TextField(blank=True, verbose_name='Сроки выполения')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('Visibility', models.CharField(choices=[('Отображать', 'Отображать'), ('Не отображать', 'Не отображать')], default='Отображать', max_length=50, verbose_name='Отображение')),
                ('Images', models.ManyToManyField(blank=True, to='web.portfolioimage', verbose_name='Изображения портфолио')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
